/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Shelter_ManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ShelterOrganization;
import Business.POJO.HomelessDirectory;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nares
 */
public class Shelter_ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Shelter_ManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private ShelterOrganization shelterOrganization;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private HomelessDirectory homelessDirectory;
    private Enterprise enterprise;
    public Shelter_ManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ShelterOrganization shelterOrganization, Enterprise enterprise, EcoSystem business) {
    
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = business;
        this.shelterOrganization = shelterOrganization;
        this.enterprise=enterprise;
        // jLabel2.setText(enterprise.getName());
       // populateTable();
        dB4OUtil.storeSystem(system);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestButton = new javax.swing.JButton();
        Viewrequest = new javax.swing.JButton();
        requestComboBox = new javax.swing.JComboBox<>();
        btbStatus = new javax.swing.JButton();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RequestButton.setBackground(new java.awt.Color(204, 255, 255));
        RequestButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        RequestButton.setText("Raise New Request");
        RequestButton.setBorder(new javax.swing.border.MatteBorder(null));
        RequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButtonActionPerformed(evt);
            }
        });
        add(RequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 264, 280, 40));

        Viewrequest.setBackground(new java.awt.Color(204, 255, 255));
        Viewrequest.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Viewrequest.setText("View Requests");
        Viewrequest.setBorder(new javax.swing.border.MatteBorder(null));
        Viewrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewrequestActionPerformed(evt);
            }
        });
        add(Viewrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 184, 280, 40));

        requestComboBox.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        requestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Admin", "Manitanance" }));
        add(requestComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 264, 206, 40));

        btbStatus.setBackground(new java.awt.Color(204, 255, 255));
        btbStatus.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btbStatus.setText("Raised Request Status");
        btbStatus.setBorder(new javax.swing.border.MatteBorder(null));
        btbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbStatusActionPerformed(evt);
            }
        });
        add(btbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 344, 280, 40));

        comboStatus.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Supplier", "Maintences_Staff" }));
        add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 344, 210, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("Shelter Manager Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 64, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButtonActionPerformed

      if(requestComboBox.getSelectedItem().equals("Food Admin")){
       ShelterSelectionPanel sheltermanager= new ShelterSelectionPanel(userProcessContainer, userAccount, shelterOrganization, enterprise, system);
       userProcessContainer.add("ShelterSelectionPanel",sheltermanager);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      }
      
      if (requestComboBox.getSelectedItem().equals("Manitanance")){
          ShelterManager_toMaintainance maintainance= new ShelterManager_toMaintainance(userProcessContainer, userAccount, shelterOrganization, enterprise, system);
        userProcessContainer.add("ShelterManager_toMaintainance",maintainance);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      }
    }//GEN-LAST:event_RequestButtonActionPerformed

    private void ViewrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewrequestActionPerformed
         ShelterManagerViewRequest viewrequest= new ShelterManagerViewRequest(userProcessContainer, userAccount, shelterOrganization, enterprise, system);
       userProcessContainer.add("ShelterManagerViewRequest",viewrequest);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ViewrequestActionPerformed

    private void btbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbStatusActionPerformed
        
        if(comboStatus.getSelectedItem().equals("Food Supplier")){
            Status_FoodSupplier statuspanel = new  Status_FoodSupplier (userProcessContainer, userAccount,shelterOrganization, enterprise, system);
            userProcessContainer.add("StatusPanelFood", statuspanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            dB4OUtil.storeSystem(system);
       
      }
      
      if (comboStatus.getSelectedItem().equals("Maintences_Staff")){
           Status_Maintences status = new  Status_Maintences(userProcessContainer, userAccount,shelterOrganization, enterprise, system);
            userProcessContainer.add("StatusPanelMaintence", status);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            dB4OUtil.storeSystem(system);
      }
        
       
        
        
        
    }//GEN-LAST:event_btbStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestButton;
    private javax.swing.JButton Viewrequest;
    private javax.swing.JButton btbStatus;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> requestComboBox;
    // End of variables declaration//GEN-END:variables
}
