/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RecruiterRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EmploymentOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RecruiterWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.network.Network;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author nares
 */
public class RecruiterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecruiterWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private EmploymentOrganization employmentOrganization;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();     
    String educationLevel;

    public RecruiterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EmploymentOrganization employmentOrganization, Enterprise enterprise, EcoSystem system ) {
       initComponents();  
       this.userProcessContainer = userProcessContainer;
       this.userAccount = account;
       this.system = system;
       this.employmentOrganization = employmentOrganization;
       this.enterprise=enterprise;
      
       populateTable();
       dB4OUtil.storeSystem(system);
    }
    
    public void populateTable(){
       
         DefaultTableModel model = (DefaultTableModel) recruiterJTable.getModel();
           model.setRowCount(0);
       
            for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request.getSender().getEmployee().getName();
            row[1] = request.getReceiver()==null?null:request.getReceiver().getEmployee().getName();;
            row[2] = request.getStatus();
            row[3] = request.getRequestDate();
            row[4] = request.getResolveDate();
          
            row[5] = ((RecruiterWorkRequest)request).getID();
            row[6] = ((RecruiterWorkRequest) request).getName();
            
            model.addRow(row);
        }  
        
        
    }
     static boolean isStringValid(String number)
    {
        String regex = "^[a-zA-Z]*$";
        return number.matches(regex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recruiterJTable = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEducationLevel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSkills = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        recruiterJTable.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        recruiterJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Status", "Request Date", "Resolve Date", "Candidate ID", "Candidate Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recruiterJTable);

        btnRequest.setBackground(new java.awt.Color(102, 102, 255));
        btnRequest.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("Raise a New Request");
        btnRequest.setBorder(new javax.swing.border.MatteBorder(null));
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("Education Level :");

        txtEducationLevel.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        txtEducationLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEducationLevelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Skills");

        txtSkills.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N

        btnRefresh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefresh.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(new javax.swing.border.MatteBorder(null));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel3.setText("Comment");

        txtComment.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel4.setText("Recruiter Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(312, 312, 312)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEducationLevel)
                                .addComponent(txtSkills)
                                .addComponent(txtComment)
                                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEducationLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEducationLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEducationLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEducationLevelActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
       if((txtEducationLevel.getText().isEmpty())||(txtSkills.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Fields can't be empty");
            return;
       }else{
           if(isStringValid(txtComment.getText()) == false||isStringValid(txtEducationLevel.getText()) == false||isStringValid(txtSkills.getText()) == false)    
        {
           
            JOptionPane.showMessageDialog(null, "Please enter a correct field ");
            return;
        }  
       String educationLevel = txtEducationLevel.getText();
       String skill =txtSkills.getText();
       Date date = new Date(); 
       
       RecruiterWorkRequest request = new RecruiterWorkRequest();
       request.setSender(userAccount);
       request.setStatus("Sent");
       request.setRequestDate(date);
       request.setRole("Recruiter");
       request.setEducation(educationLevel);
       request.setSkill(skill);
       request.setMessage(txtComment.getText());
       
       
        dB4OUtil.storeSystem(system);
        Organization org = null;
          for (Network network: system.getNetworkList()){

                    for (Enterprise enterprisetemp: network.getEnterpriseDirectory().getEnterpriseList()){

                        for (Organization organization : enterprisetemp.getOrganizationDirectory().getOrganizationList()){
                            if (organization instanceof NGOOrganization){
                                org = organization;
                                break;
                            }
                        }}}
                        if (org!=null){
                            org.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                            JOptionPane.showMessageDialog(null, "Requested" );
                            populateTable();
                            txtComment.setText("");
                            txtEducationLevel.setText("");
                            txtSkills.setText("");
                             
                             dB4OUtil.storeSystem(system);
                        }
       }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
         populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recruiterJTable;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtEducationLevel;
    private javax.swing.JTextField txtSkills;
    // End of variables declaration//GEN-END:variables
}
