/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Surya
 */
public class EnterpriseAdminUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminUpdatePanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount useraccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public EnterpriseAdminUpdatePanel(JPanel userProcessContainer, EcoSystem system, UserAccount useraccount) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.system = system;
         this.useraccount=useraccount;
         populatefields();
         }
    
    public void populatefields(){
        nameTxt.setText(useraccount.getEmployee().getName());
        userNameTxt.setText(useraccount.getUsername());
        passwordTxt.setText(useraccount.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("UserName");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 176, -1, 40));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 336, -1, 40));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 256, -1, 40));

        userNameTxt.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 176, 117, 40));

        nameTxt.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 344, 117, 40));

        submitButton.setBackground(new java.awt.Color(102, 102, 255));
        submitButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(new javax.swing.border.MatteBorder(null));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 413, 90, 40));

        passwordTxt.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 256, 117, 40));

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.setBorder(new javax.swing.border.MatteBorder(null));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 96, 80, 40));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel4.setText("Enterprise Admin Update Panel");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 16, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         String username = userNameTxt.getText();
        String password = String.valueOf(passwordTxt.getPassword());
        String name = nameTxt.getText();
        
        if((name == null || name.equals("")) || (username == null || username.equals(""))){
        JOptionPane.showMessageDialog(null, "Name field cannot be empty");
         }else{
        if(! passwordPatternCorrect()) {
         JOptionPane.showMessageDialog(null, "Password must be at least 4 characters, no more than 8 characters, and must include at least one upper case letter, one lower case letter, and one numeric digit");
         passwordTxt.setBorder(BorderFactory.createLineBorder(Color.RED));
         jLabel3.setForeground(Color.red);
         //return;
         }else{
        
        useraccount.setUsername(userNameTxt.getText());
        useraccount.setPassword(String.valueOf(passwordTxt.getPassword()));
        Employee employee=useraccount.getEmployee();
        employee.setName(nameTxt.getText());
         dB4OUtil.storeSystem(system);
         JOptionPane.showMessageDialog(null,"Updated Successfully");
         userNameTxt.setEditable(false);
         passwordTxt.setEditable(false);
         nameTxt.setEditable(false);
        }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        Component[] comps=userProcessContainer.getComponents();
        for (Component comp:comps)
        {
            if (comp instanceof ManageEnterpriseAdminJPanel)
            {
            ManageEnterpriseAdminJPanel adminJpanel=(ManageEnterpriseAdminJPanel) comp;
            adminJpanel.populateTable();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

     boolean passwordPatternCorrect() {
       Pattern p = Pattern.compile("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{4,8}$");
       Matcher m = p.matcher(passwordTxt.getText());
       boolean b = m.matches();
       return b;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
