/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Surya
 */
public class NetworkUpdateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkUpdateJpanel
     */
    private Network network;
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    NetworkUpdateJpanel(JPanel userProcessContainer, Network network, EcoSystem system) {
        initComponents();
        this.network = network;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameJUpdateTxt = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 40));

        nameJUpdateTxt.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        nameJUpdateTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(nameJUpdateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 170, 40));

        submitButton.setBackground(new java.awt.Color(102, 102, 255));
        submitButton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Update");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 260, 110, 40));

        Backbutton.setBackground(new java.awt.Color(102, 102, 102));
        Backbutton.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("<<Back");
        Backbutton.setBorder(new javax.swing.border.MatteBorder(null));
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        add(Backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 40));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("Network Update  Panel");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

        if (nameJUpdateTxt.getText() == null || nameJUpdateTxt.getText() == " ") {
            JOptionPane.showMessageDialog(null, "Please enter Network name");
        } else {
            if (system.checkifNetworkIsUnique(nameJUpdateTxt.getText())) {
                network.setName(nameJUpdateTxt.getText());
                dB4OUtil.storeSystem(system);
                JOptionPane.showMessageDialog(null, "Network name updated Successfully");
                nameJUpdateTxt.setEditable(false);

            } else {
                JOptionPane.showMessageDialog(null, "Please enter a Unique Network");
            }
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Component[] comps = userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageNetworkJPanel) {
                ManageNetworkJPanel manageNetwrok = (ManageNetworkJPanel) comp;
                manageNetwrok.populateNetworkTable();
            }
        }
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_BackbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameJUpdateTxt;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
